// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: transport/transport.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationalData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Occupancy     int32                  `protobuf:"varint,3,opt,name=occupancy,proto3" json:"occupancy,omitempty"`
	VehicleStatus string                 `protobuf:"bytes,4,opt,name=vehicle_status,json=vehicleStatus,proto3" json:"vehicle_status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationalData) Reset() {
	*x = OperationalData{}
	mi := &file_transport_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationalData) ProtoMessage() {}

func (x *OperationalData) ProtoReflect() protoreflect.Message {
	mi := &file_transport_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationalData.ProtoReflect.Descriptor instead.
func (*OperationalData) Descriptor() ([]byte, []int) {
	return file_transport_transport_proto_rawDescGZIP(), []int{0}
}

func (x *OperationalData) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *OperationalData) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *OperationalData) GetOccupancy() int32 {
	if x != nil {
		return x.Occupancy
	}
	return 0
}

func (x *OperationalData) GetVehicleStatus() string {
	if x != nil {
		return x.VehicleStatus
	}
	return ""
}

func (x *OperationalData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_transport_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_transport_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_transport_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transport_transport_proto protoreflect.FileDescriptor

const file_transport_transport_proto_rawDesc = "" +
	"\n" +
	"\x19transport/transport.proto\x12\ttransport\"\xb0\x01\n" +
	"\x0fOperationalData\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1c\n" +
	"\toccupancy\x18\x03 \x01(\x05R\toccupancy\x12%\n" +
	"\x0evehicle_status\x18\x04 \x01(\tR\rvehicleStatus\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2Z\n" +
	"\x10TransportService\x12F\n" +
	"\x13SendOperationalData\x12\x1a.transport.OperationalData\x1a\x13.transport.ResponseB\x0eZ\f./;transportb\x06proto3"

var (
	file_transport_transport_proto_rawDescOnce sync.Once
	file_transport_transport_proto_rawDescData []byte
)

func file_transport_transport_proto_rawDescGZIP() []byte {
	file_transport_transport_proto_rawDescOnce.Do(func() {
		file_transport_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_transport_proto_rawDesc), len(file_transport_transport_proto_rawDesc)))
	})
	return file_transport_transport_proto_rawDescData
}

var file_transport_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_transport_proto_goTypes = []any{
	(*OperationalData)(nil), // 0: transport.OperationalData
	(*Response)(nil),        // 1: transport.Response
}
var file_transport_transport_proto_depIdxs = []int32{
	0, // 0: transport.TransportService.SendOperationalData:input_type -> transport.OperationalData
	1, // 1: transport.TransportService.SendOperationalData:output_type -> transport.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_transport_proto_init() }
func file_transport_transport_proto_init() {
	if File_transport_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_transport_proto_rawDesc), len(file_transport_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_transport_proto_goTypes,
		DependencyIndexes: file_transport_transport_proto_depIdxs,
		MessageInfos:      file_transport_transport_proto_msgTypes,
	}.Build()
	File_transport_transport_proto = out.File
	file_transport_transport_proto_goTypes = nil
	file_transport_transport_proto_depIdxs = nil
}
